### PR TITLE
Replace <hr> by CSS border

### PR DESCRIPTION
**Pull request by emillon**
Markdown files used to embed `---` to render an horizontal line.
This uses a CSS rule instead to add a line below `<h1>` and `<h2>` elements in `<main>`.

### CODE REVIEW

**Comment by emillon** [comment]
Spacing is not completely the same as before but I think it works fine. Let me know what you think.

**Review by patricoferris — APPROVED** [review]
LGTM -- had a brief look into deploy previews which would be 💯 but I'm not sure it's possible when the build lies outside of Netlify (in the GA). 

Also the `opam depext -yt`bug has reared its head in the test suite, do you think just removing `-t` is fine (I think it will work, but does this need fixed in the `depext` plugin)?

**Comment by emillon** [comment]
Regarding `opam depext`, I don't use it enough to see if that's a problem. I think that that we don't really need `-t`, AND that `-t` should only consider test deps for this package and not its deps.

For preview deploys, I think you should be able to do it from an action, e.g. https://github.com/marketplace/actions/netlify-actions. Being able to use ocamlci for that would be useful but it's not there yet I'm afraid.

**Comment by patricoferris** [comment]
> Regarding `opam depext`, I don't use it enough to see if that's a problem. I think that that we don't really need `-t`, AND that `-t` should only consider test deps for this package and not its deps.

Hmm I copied it from `ocaml-yaml` as it seems to be some sort of standard way to setup CI (especially GA) --https://github.com/search?q=opam+depext+-yt&type=Code

> For preview deploys, I think you should be able to do it from an action, e.g. https://github.com/marketplace/actions/netlify-actions. Being able to use ocamlci for that would be useful but it's not there yet I'm afraid.

Cool, thanks will look into this :)) Once the tests pass feel free to merge 👍

**Pull request merged**
